PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Employee (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  DateOfBirth TEXT,
  Address TEXT,
  Email TEXT NOT NULL,
  UserName TEXT NOT NULL UNIQUE,
  Password TEXT NOT NULL,
  Role INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Location (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Address TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Movie (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Title TEXT NOT NULL,
  Duration INTEGER NOT NULL,
  MinimunAge INTEGER NOT NULL,
  MovieCast TEXT
);

CREATE TABLE IF NOT EXISTS MovieRoom (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  RoomNumber INTEGER NOT NULL,
  RoomLayoutJson TEXT NOT NULL,
  SupportedMovieType INTEGER NOT NULL,
  LocationId INTEGER NOT NULL,
  FOREIGN KEY (LocationId) REFERENCES Location (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Schedule (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  MovieRoomId INTEGER NOT NULL,
  MovieId INTEGER NOT NULL,
  StartDate DATETIME NOT NULL,
  FOREIGN KEY (MovieRoomId) REFERENCES MovieRoom (Id) ON DELETE CASCADE,
  FOREIGN KEY (MovieId) REFERENCES Movie (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Reservation (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  PhoneNumber INTEGER NOT NULL,
  EMail TEXT NOT NULL,
  ReservationNumber TEXT NOT NULL UNIQUE,
  OrderId INTEGER NOT NULL,
  Paid INTEGER NOT NULL CHECK (Paid IN (0, 1)),
  FOREIGN KEY (OrderId) REFERENCES CustomerOrder (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ScheduleSeat (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ScheduleId INTEGER NOT NULL,
  ReservationId INTEGER NOT NULL,
  Price REAL NOT NULL,
  Type INTEGER NOT NULL,
  SeatNumber TEXT NOT NULL,
  FOREIGN KEY (ScheduleId) REFERENCES Schedule (Id) ON DELETE CASCADE,
  FOREIGN KEY (ReservationId) REFERENCES Reservation (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CustomerOrder (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  GrandPrice REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderLine (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  OrderId INTEGER NOT NULL,
  Quantity INTEGER NOT NULL,
  Description TEXT NOT NULL,
  VatPercentage INTEGER NOT NULL,
  Price REAL NOT NULL,
  FOREIGN KEY (OrderId) REFERENCES CustomerOrder (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DiscountCode (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Code TEXT NOT NULL,
  DiscountAmount REAL NOT NULL,
  DiscountType TEXT NOT NULL,
  ExperationDate DATETIME NOT NULL,
  OrderId INTEGER NOT NULL,
  FOREIGN KEY (OrderId) REFERENCES CustomerOrder (Id) ON DELETE CASCADE
);
